// Auto-generated by LibreLane
module rv32i_core(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rstB,
  input clkEn,
  output[31:0] pc,
  input[31:0] inst_in,
  output[31:0] addr,
  output[31:0] dataBusOut,
  output wrEn,
  output rdEn,
  output[3:0] RamMode,
  input[31:0] dataBusIn,
  input dataBusInEn
);
endmodule
