set_property IOSTANDARD LVCMOS33 [get_ports {pin[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports progEnB]
set_property IOSTANDARD LVCMOS33 [get_ports rstB]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports statusLED]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property PACKAGE_PIN J20 [get_ports {pin[7]}]
set_property PACKAGE_PIN L16 [get_ports {pin[6]}]
set_property PACKAGE_PIN M17 [get_ports {pin[5]}]
set_property PACKAGE_PIN D19 [get_ports {pin[4]}]
set_property PACKAGE_PIN E18 [get_ports {pin[3]}]
set_property PACKAGE_PIN M15 [get_ports {pin[2]}]
set_property PACKAGE_PIN K16 [get_ports {pin[1]}]
set_property PACKAGE_PIN J16 [get_ports {pin[0]}]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN N16 [get_ports progEnB]
set_property PACKAGE_PIN N15 [get_ports rstB]
set_property PACKAGE_PIN F19 [get_ports rx]
set_property PACKAGE_PIN G19 [get_ports tx]
set_property PACKAGE_PIN M14 [get_ports statusLED]
create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
set_false_path -from [get_ports {pin[*]}] -to [get_clocks clk]

set_property IOSTANDARD LVCMOS33 [get_ports rx_echo]
set_property PACKAGE_PIN J18 [get_ports rx_echo]
