set_property IOSTANDARD LVCMOS33 [get_ports {pin[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports progEnB]
set_property IOSTANDARD LVCMOS33 [get_ports rstB]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports statusLED]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property PACKAGE_PIN J20 [get_ports {pin[7]}]
set_property PACKAGE_PIN L16 [get_ports {pin[6]}]
set_property PACKAGE_PIN M17 [get_ports {pin[5]}]
set_property PACKAGE_PIN D19 [get_ports {pin[4]}]
set_property PACKAGE_PIN E18 [get_ports {pin[3]}]
set_property PACKAGE_PIN M15 [get_ports {pin[2]}]
set_property PACKAGE_PIN K16 [get_ports {pin[1]}]
set_property PACKAGE_PIN J16 [get_ports {pin[0]}]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN N16 [get_ports progEnB]
set_property PACKAGE_PIN N15 [get_ports rstB]
set_property PACKAGE_PIN F19 [get_ports rx]
set_property PACKAGE_PIN G19 [get_ports tx]
set_property PACKAGE_PIN M14 [get_ports statusLED]
create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
set_false_path -from [get_ports {pin[*]}] -to [get_clocks clk]

set_property IOSTANDARD LVCMOS33 [get_ports rx_echo]
set_property PACKAGE_PIN J18 [get_ports rx_echo]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 13 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {wProgRamAddr[2]} {wProgRamAddr[3]} {wProgRamAddr[4]} {wProgRamAddr[5]} {wProgRamAddr[6]} {wProgRamAddr[7]} {wProgRamAddr[8]} {wProgRamAddr[9]} {wProgRamAddr[10]} {wProgRamAddr[11]} {wProgRamAddr[12]} {wProgRamAddr[13]} {wProgRamAddr[14]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 10 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {wCoreAddr[0]} {wCoreAddr[1]} {wCoreAddr[2]} {wCoreAddr[3]} {wCoreAddr[4]} {wCoreAddr[5]} {wCoreAddr[6]} {wCoreAddr[7]} {wCoreAddr[8]} {wCoreAddr[9]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
